# Importing Libraries

In [157]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

# Data Collection & Analysis

## Load Kidney Disease Dataset

In [158]:
kidney_data = pd.read_csv('/Users/macbookpro/Desktop/End-to-End Projects/kidney_disease/data/kidney_disease_dataset.csv')
kidney_data

,Age,Creatinine_Level,BUN,Diabetes,Hypertension,GFR,Urine_Output,CKD_Status,Dialysis_Needed
0,71,0.30,40.9,0,1,46.8,1622.0,1,0
1,34,1.79,17.1,0,0,43.8,1428.0,1,0
2,80,2.67,15.0,0,1,78.2,1015.0,1,0
3,40,0.97,31.1,0,1,92.8,1276.0,1,0
4,43,2.05,22.8,1,1,62.2,1154.0,0,0
...,...,...,...,...,...,...,...,...,...
2299,89,1.11,5.0,1,0,55.1,1344.0,1,0
2300,89,0.30,5.0,0,0,47.5,2156.0,1,0
2301,84,0.30,7.3,1,0,120.0,1353.0,0,0
2302,24,1.58,26.4,1,0,75.6,1067.0,0,0
2303,21,0.63,27.1,1,0,50.7,393.0,1,0

In [159]:
# first 5 rows
kidney_data.head()

,Age,Creatinine_Level,BUN,Diabetes,Hypertension,GFR,Urine_Output,CKD_Status,Dialysis_Needed
0,71,0.30,40.9,0,1,46.8,1622.0,1,0
1,34,1.79,17.1,0,0,43.8,1428.0,1,0
2,80,2.67,15.0,0,1,78.2,1015.0,1,0
3,40,0.97,31.1,0,1,92.8,1276.0,1,0
4,43,2.05,22.8,1,1,62.2,1154.0,0,0

In [160]:
# last 5 rows
kidney_data.tail()

,Age,Creatinine_Level,BUN,Diabetes,Hypertension,GFR,Urine_Output,CKD_Status,Dialysis_Needed
2299,89,1.11,5.0,1,0,55.1,1344.0,1,0
2300,89,0.30,5.0,0,0,47.5,2156.0,1,0
2301,84,0.30,7.3,1,0,120.0,1353.0,0,0
2302,24,1.58,26.4,1,0,75.6,1067.0,0,0
2303,21,0.63,27.1,1,0,50.7,393.0,1,0

In [161]:
# info of the dataset
kidney_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2304 entries, 0 to 2303
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               2304 non-null   int64
 1   Creatinine_Level  2304 non-null   float64
 2   BUN               2304 non-null   float64
 3   Diabetes          2304 non-null   int64
 4   Hypertension      2304 non-null   int64
 5   GFR               2304 non-null   float64
 6   Urine_Output      2304 non-null   float64
 7   CKD_Status        2304 non-null   int64
 8   Dialysis_Needed   2304 non-null   int64
dtypes: float64(4), int64(5)
memory usage: 162.1 KB

In [162]:
# dataset description
kidney_data.describe()

,Age,Creatinine_Level,BUN,Diabetes,Hypertension,GFR,Urine_Output,CKD_Status,Dialysis_Needed
count,2304.000000,2304.000000,2304.000000,2304.000000,2304.000000,2304.000000,2304.000000,2304.000000,2304.000000
mean,54.159288,1.305638,18.813672,0.406684,0.498264,68.953863,1309.189670,0.508681,0.013455
std,20.513729,0.789594,10.508358,0.491322,0.500106,24.660191,491.951914,0.500033,0.115237
min,20.000000,0.300000,5.000000,0.000000,0.000000,5.000000,100.000000,0.000000,0.000000
25%,36.000000,0.620000,9.975000,0.000000,0.000000,51.300000,967.750000,0.000000,0.000000
50%,54.000000,1.240000,18.200000,0.000000,0.000000,69.150000,1295.500000,1.000000,0.000000
75%,72.000000,1.842500,26.000000,1.000000,1.000000,86.300000,1633.500000,1.000000,0.000000
max,90.000000,4.130000,61.900000,1.000000,1.000000,120.000000,2899.000000,1.000000,1.000000

In [163]:
# check for missing values
kidney_data.isnull().sum()

Age                 0
Creatinine_Level    0
BUN                 0
Diabetes            0
Hypertension        0
GFR                 0
Urine_Output        0
CKD_Status          0
Dialysis_Needed     0
dtype: int64

In [164]:
# check the distribution of the Dialysis_Needed column
kidney_data['Dialysis_Needed'].value_counts()

Dialysis_Needed
0    2273
1      31
Name: count, dtype: int64

## 0 ==> Dialysis ABSENT
## 1 ==> Dialysis PRESENT

In [165]:
# group the last column by mean
kidney_data.groupby('Dialysis_Needed').mean()

,Age,Creatinine_Level,BUN,Diabetes,Hypertension,GFR,Urine_Output,CKD_Status
Dialysis_Needed,,,,,,,,
0,54.199296,1.304030,18.833436,0.405631,0.500220,69.780730,1310.983722,0.50198
1,51.225806,1.423548,17.364516,0.483871,0.354839,8.325806,1177.645161,1.00000

In [166]:
# separate FEATURES from the TARGET
X = kidney_data.drop(columns='Dialysis_Needed', axis=1)
Y = kidney_data['Dialysis_Needed']

In [167]:
print(X)

      Age  Creatinine_Level   BUN  Diabetes  Hypertension    GFR  \
0      71              0.30  40.9         0             1   46.8
1      34              1.79  17.1         0             0   43.8
2      80              2.67  15.0         0             1   78.2
3      40              0.97  31.1         0             1   92.8
4      43              2.05  22.8         1             1   62.2
...   ...               ...   ...       ...           ...    ...
2299   89              1.11   5.0         1             0   55.1
2300   89              0.30   5.0         0             0   47.5
2301   84              0.30   7.3         1             0  120.0
2302   24              1.58  26.4         1             0   75.6
2303   21              0.63  27.1         1             0   50.7

      Urine_Output  CKD_Status
0           1622.0           1
1           1428.0           1
2           1015.0           1
3           1276.0           1
4           1154.0           0
...            ...         ...
2299        1344.0           1
2300        2156.0           1
2301        1353.0           0
2302        1067.0           0
2303         393.0           1

[2304 rows x 8 columns]

In [168]:
print(Y)

0       0
1       0
2       0
3       0
4       0
       ..
2299    0
2300    0
2301    0
2302    0
2303    0
Name: Dialysis_Needed, Length: 2304, dtype: int64

In [169]:
# print the columns length and details
print(X.columns)
print(len(X.columns))

Index(['Age', 'Creatinine_Level', 'BUN', 'Diabetes', 'Hypertension', 'GFR',
       'Urine_Output', 'CKD_Status'],
      dtype='object')
8

# Data Splitting

### Train Test Split

In [170]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.4, stratify=Y, random_state=42
)

In [171]:
# no of X train and test shape
print(X.shape, X_train.shape, X_test.shape)

(2304, 8) (1382, 8) (922, 8)

# Model Training

In [172]:
# train the model using SVC
classifier = svm.SVC(kernel='linear')

In [173]:
# fit the model
classifier.fit(X_train, y_train)

SVC(kernel='linear')

# Model Evaluation

## Accuracy Score on Training Data

In [174]:
# train data
X_train_pred = classifier.predict(X_train)
train_acc = accuracy_score(X_train_pred, y_train)

In [175]:
print("Result on Training Data: ",train_acc)

Result on Training Data:  1.0

## Accuracy Score on Testing Data

In [176]:
X_test_pred = classifier.predict(X_test)
test_acc = accuracy_score(X_test_pred, y_test)

In [177]:
print("Result on Testing Data: ", test_acc)

Result on Testing Data:  0.9989154013015185

# Predictive System

In [178]:
# load the dataset data
input_data = (71,0.3,40.9,0,1,46.8,1622,1) # Dialysis Absent
input_data = (42,3.14,50.3,1,1,120,2656,1) # Dialysis Present


# change the input data into a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array
input_reshaped = input_data_as_numpy_array.reshape(1,-1)

# make predictions
predictions = classifier.predict(input_reshaped)
print(predictions)

# system check
if (predictions[0] == 1):
    print('DIALYSIS ABSENT')
else:
    print("DIALYSIS PRESENT")

[0]
DIALYSIS PRESENT

/opt/miniconda3/envs/churn_ml/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [179]:
# # load the dataset data
# # input_data = (71,0.3,40.9,0,1,46.8,1622,1) # Dialysis Absent
# input_data = (42,3.14,50.3,1,1,120,2656,1) # Dialysis Present


# # change the input data into a numpy array
# input_data_as_numpy_array = np.asarray(input_data)

# # reshape the array
# input_reshaped = input_data_as_numpy_array.reshape(1,-1)

# # make predictions
# predictions = classifier.predict(input_reshaped)
# print(predictions)

# # system check
# if (predictions[0] == 1):
#     print('DIALYSIS PRESENT')
# else:
#     print("DIALYSIS ABSENT")

# Save the trained model

In [180]:
import pickle

In [181]:
filename = 'kidney_model.sav'
pickle.dump(classifier, open(filename, 'wb'))

In [182]:
loaded_model = pickle.load(open('/Users/macbookpro/Desktop/End-to-End Projects/kidney_disease/model/kidney_model.sav', 'rb'))